#!/bin/bash
if [ "$1" != "" ]; then
    cd $1
fi

if [ ! -f "AndroidManifest.xml" ];then
    echo "no AndroidManifest.xml!!!!"
    exit
fi

startTime=$(date +%s)

configFile="pack.config"

#import base functions 
source android-manifest


#remove folder crunch in bin of project
print_divider
echo "remove crunch"
print_divider
clean_crunch_in_bin

#generate build
print_divider
echo "generating config"
print_divider
ant_build_config

DEBUG=false;
if [ ! -f "$configFile" ]; then
    ant auto-release -DUMENG_CHANNEL=official -DDEBUG_MODE=$DEBUG
    #ant auto-release 
    #ant auto-debug -DUMENG_CHANNEL=googlePlayStore
else
    #cat $configFile | grep package
    cat $configFile | grep "channel="  | awk -F\= '{print $2}' |  while read line
    do
        echo "PACKAGING channel $line"
        ant auto-release -DUMENG_CHANNEL=$line -DDEBUG_MODE=$DEBUG
        echo
        echo
    done
fi

echo
echo "----------------------------------------------"
echo "duration is $(expr $(date +%s) - $startTime)"
echo
